### ISSUE TITLE
NFS-Client "reclaimPolicy: Delete" doesn't delete.

### ISSUE THREAD

**Issue by jgreat** [kubernetes-incubator/external-storage#596] opened 2018-02-09 02:39 UTC
I was expecting `reclaimPolicy: Delete` to actually delete the created directory on my nfs server. 

Unless I'm missing something the current behavior for Delete is to actually move the directory to an "archive" directory leaving old data laying around.

Is there a process that comes and cleans up these archive directories?

Would you accept a PR to configure this behavior with a ENV var or something?

**Comment by wongma7** [comment] 2018-02-25 10:06
yeah it should delete I don't remember why I approved the 'archive' behavior, it sounds plain wrong. Since it would be dangerous to change it now yes a PR to configure it would be acceptable

**Comment by wongma7** [comment] 2018-06-15 19:52
open to PRs, will need to tread carefully in case anybody relies on this (nonstandard) behavior

**Comment by gmorse81** [comment] 2018-08-07 20:00
Hello, 

I would be willing to take this on since i need it, but im not sure how to handle the current behavior. Since the default reclaim policy for a storage class is "delete", if i were to honor that it would change the default behavior for anyone who installed this previously. especially since the image reference in the deployment is "latest".

any thoughts on approach?

**Comment by travisghansen** [comment] 2018-08-07 22:01
I would introduce it as a `parameter` to the storage class.

**Comment by gmorse81** [comment] 2018-08-07 23:09
The issue is backward compatibility. By default, the reclaimPolicy on a storage class is "delete". Right now anyone who has installed this likely has that on their storage class, but the current behavior is to create this archive directory. so... if i were to simply implement the reclaimPolicy enforcement, it may cause unexpected behavior for those who upgrade their container image in the deployment. they would start to have their old directories getting deleted instead of archived. 

While this does correct the issue and implement the behavior expected, it would make an unexpected change for those already running this. 

Personally, i think its best to tear of the bandaid, but I'm not going to write the code and have the PR rejected because of this.

**Comment by gmorse81** [comment] 2018-08-07 23:37
guess i should have read your one line a little closer, lol. you are suggesting using a parameter on the storageclass to determine if "delete" should either delete or archive. that makes sense. 

so how about:

parameters:
  delete-archive: true //or false

This would default to false for backwards compat.

**Comment by wongma7** [comment] 2018-08-08 00:00
sgtm, though should be camelcase. I can't think of a better name but it doesn't matter much because people will only be able to discover it by reading our docs/yamls anyway. I am thinking it would be safe to edit our class.yaml to set it this true, so anybody starting anew will get the expected "Delete is actually delete" behavior and anyone already running will continue to get "Delete is archive"

**Comment by travisghansen** [comment] 2018-08-08 12:57
`respectReclaimPolicy` maybe?  If the reclaim policy on the PV gets updated to retain even if the new parameter is true you'd still want to archive yeah?

**Comment by wongma7** [comment] 2018-08-08 13:47
No, the "archiving" is non-standard behaviour that can't be represented with either Retain or Delete. Anyway, a PV with Retain will never make it to the provisioner because we ignore it at the controller https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L887

**Comment by gmorse81** [comment] 2018-08-08 13:53
Thanks. Yeah, i realized that when i started digging into the code. 

unless there are objections, I've landed on "archiveOnDelete:"

**Comment by travisghansen** [comment] 2018-08-08 21:30
@wongma7 Yep.  I realized that after I commented earlier.  Thanks for clearing it up!

**Closed** 2018-08-09 16:12 UTC
Labels: area/nfs-client
