### ISSUE TITLE
[aws efs] ProvisioningFailed - no volume plugin matched

### ISSUE THREAD

**Issue by harik8** [kubernetes-incubator/external-storage#1111] opened 2019-01-24 20:13 UTC
I followed the deployment steps and deployed efs-provisioner on kubernetes. But I am getting below error, 

```
$ kubectl describe pvc efs -n dev
Name:		efs
Namespace:	dev
StorageClass:	aws-efs
Status:		Pending
Volume:		
Labels:		<none>
Annotations:	volume.beta.kubernetes.io/storage-class=aws-efs
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  8m		23s		11	persistentvolume-controller			Warning		ProvisioningFailed	no volume plugin matched
```

**Comment by Art3mK** [comment] 2019-02-08 10:22
I'm having the same issue on EKS, and don't know how to debug it. There are no any erros in efs-provisioner pod logs, EFS is mounted by efs-provisioner, but pvcs are pending with that `no volume plugin matched` message.

**Comment by Art3mK** [comment] 2019-02-08 12:57
Looks like it's smth with latest versions. Works fine with chart version `0.1.3` (which uses `0.1.2` image) In order to provision PVC with `0.2.0` chart and `v2.1.0-k8s1.11` image you'll need to add `volume.beta.kubernetes.io/storage-provisioner: %your provisionerName%` annotation to your PVC.

provisioner name could be checked in storage class:
```
➜  ~ kubectl get storageclasses.storage.k8s.io efs -o yaml --export                                                     
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: null
  labels:
    app: efs-provisioner
    chart: efs-provisioner-0.1.3
    env: dev
    heritage: Tiller
    release: efs-provisioner
  name: efs
  selfLink: /apis/storage.k8s.io/v1/storageclasses/efs
parameters:
  gidAllocate: "true"
  gidMax: "50000"
  gidMin: "40000"
provisioner: kubernetes.io/aws-efs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by wongma7** [comment] 2019-03-04 15:49
what version of kubernetes?

/area aws/efs

**Comment by Art3mK** [comment] 2019-03-04 15:55
We are using EKS one

Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by wongma7** [comment] 2019-03-04 16:01
what does the StorageClass aws-efs look like?

**Comment by wongma7** [comment] 2019-03-04 16:02
nvm, I see it above. The issue is that provisioner is "kubernetes.io/aws-efs". It can't begin with kubernetes.io as that is reserved by kubernetes

**Comment by pulpbill** [comment] 2019-03-31 23:37
> 
> 
> nvm, I see it above. The issue is that provisioner is "kubernetes.io/aws-efs". It can't begin with kubernetes.io as that is reserved by kubernetes

I have the same issue and using kubernetes.io/aws-efs, what should I use then? Thanks.

**Comment by Art3mK** [comment] 2019-04-01 05:17
IIUC you just need to change provisioner name, as `kubernetes.io` is reserved. i.e. if you are using efs-provisioner helm chart – set `efsProvisioner.provisionerName` to some other value.

**Closed** 2019-08-29 07:33 UTC
Labels: area/aws/efs, lifecycle/rotten
