### ISSUE TITLE
Snapshot Controller - Failed to initialize cloudprovider AWS

### ISSUE THREAD

**Issue by smiddleton1** [kubernetes-incubator/external-storage#741] opened 2018-04-25 09:41 UTC
Env: Single node K8S cluster running in AWS, deployed from KOPS.

Using the Snapshot AWS example I've deployed the snapshot controller and provisioner successfully in my environment but when I inspect the logs for the controllers I've come across the following issue with AWS cloudprovider

Logs:

> I0425 07:38:43.240401       1 aws.go:822] Building AWS cloudprovider
> I0425 07:38:43.240522       1 aws.go:785] Zone not specified in configuration file; querying AWS metadata service
> W0425 07:38:43.595448       1 snapshot-controller.go:137] failed to initialize cloudprovider: could not init cloud provider "aws": error finding instance i-1234565678990: error listing AWS instances: RequestError: send request failed
> caused by: Post https://ec2.eu-west-2.amazonaws.com/: x509: failed to load system roots and no roots provided, supported cloudproviders are []string{"aws", "gce", "openstack"}
> I0425 07:38:43.595477       1 snapshot-controller.go:94] starting snapshot controller
> I0425 07:38:43.595628       1 snapshot-controller.go:168] Starting snapshot controller

Consequently I'm unable to take a working snapshot of a persistent volume. It appears it might be some sort of certificate issue?

/area snapshot

**Comment by tsmetana** [comment] 2018-05-11 12:16
Hello. I assume you start the controller and provisioner from the command line, right? Do you have the CA certificates installed correctly?

**Comment by tsmetana** [comment] 2018-06-20 08:14
I'm unable to reproduce the issue, closing.

**Closed by tsmetana** 2018-06-20 08:14 UTC
Labels: area/snapshot
