### ISSUE TITLE
[aws-efs] provide option to skip creation of new folder and use root

### ISSUE THREAD

**Issue by ashish4github** [kubernetes-incubator/external-storage#1178] opened 2019-05-30 23:49 UTC
Provide an option to skip the creation of new folder for a persistence volume claim. This allows use of a shared folder between EKS cluster and other non EKS nodes/services. In our specific use case, we want to ingest data and stoe in EFS folders. These folders will then be accessed form Pods running in EKS to read the files.

**Comment by RaySirX** [comment] 2019-06-04 16:56
Would this PR address this issue?

https://github.com/kubernetes-incubator/external-storage/pull/1147

**Comment by midN** [comment] 2019-06-04 17:04
You can use my branch.
https://github.com/kubernetes-incubator/external-storage/compare/master...midN:efs-new-options

I tried getting that merged, Google team has ignored my PR for months.
They don't seem very keen on people doing opensource contributions to Kube.

**Comment by balvey** [comment] 2019-06-24 15:49
> You can use my branch.
> [master...midN:efs-new-options](https://github.com/kubernetes-incubator/external-storage/compare/master...midN:efs-new-options)
> 
> I tried getting that merged, Google team has ignored my PR for months.
> They don't seem very keen on people doing opensource contributions to Kube.

I need the same options as you've tried to get them to merge. i'm trying to use your branch and getting an error. 
forgive my ignorance here, i'm not very familiar with go or using forked repos. I'm assuming you don't have an image already built and inside a public repo, so I need to build it myself and get it into a repo to pull from within my k8s cluster. 

I'm assuming the proper approach here is to: 

- clone your repo / fork of this repo
- checkout -b efs-new-options
- make quick-container 
- docker tag 
- docker push to my repo
- deploy within my k8s cluster using my public repo with the tag I supplied

I get the following error when doing the above. 
`/efs-provisioner flag redefined: log_dir
panic: /efs-provisioner flag redefined: log_dir
 goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000094120, 0x159ed00, 0x214fe70, 0x13da152, 0x7, 0x1405662, 0x2f)
	/usr/local/go/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc000094120, 0x214fe70, 0x13da152, 0x7, 0x0, 0x0, 0x1405662, 0x2f)
	/usr/local/go/src/flag/flag.go:708 +0x8a
github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog.InitFlags(0xc000094120)
	/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog/klog.go:411 +0x7b
main.main()
	/go/src/github.com/kubernetes-incubator/external-storage/aws/efs/cmd/efs-provisioner/efs-provisioner.go:275 +0x3c`

Also, before finding your fork, I tried modifying the go code myself and got the same errors. I'm thinking it looks like a dependency issue with logging, but I wasn't expecting the need to setup other dependencies based off the readme file on building this locally.

**Comment by midN** [comment] 2019-06-24 18:02
@balvey yeah the build logic is awkward, you need to build it outside of efs folder, in the root dir, with the vendor folder.
I pushed it to `m1dn/efs-provisioner:v1.0` - https://cloud.docker.com/repository/registry-1.docker.io/m1dn/efs-provisioner

**Comment by wongma7** [comment] 2019-06-24 18:07
@midN I'm sorry for neglecting your PR (among others). If it's a CLA issue, unfortunately I don't know how to get the attention of somebody from CNCF any more than you do. (Nobody here works for Google, I'm basically the sole maintainer.)

**Comment by midN** [comment] 2019-06-24 19:23
@wongma7 It's fine, as you said, i couldn't get past CLA anyway.

I sent them few emails on the support page, tried all solutions i could find, opened JIRA ticket on their board, tried slack messages etc, pointless.
Everything ignored, not a single answer

**Comment by ashish4github** [comment] 2019-06-24 22:19
@midN  Thanks for the fork. I have seen it and it will work for us. 
It would be great to have this included in the main release.
@wongma7  Is it possible for you to include it in main branch and release a version. We want to make sure we get any new development fixes so that we do not have to continuously merge the two.

**Comment by midN** [comment] 2019-06-25 13:50
@ashish4github @wongma7 I can reopen the PR, but again, i can't get past the CLA.
I've submitted multiple Support requests, tried reaching out on all channels, no luck.

The CLA is ridiculous.
My commits are signed with valid email, same email used for Linux Foundation registration.

**Comment by saikiran243** [comment] 2019-07-11 10:53
Hi @midN can u specify steps on how to deploy this. when i tried to clone your repo and apply the manifest file. (by filling out my env details in it) the container is not getting created. 
NAME                               READY     STATUS              RESTARTS   AGE
efs-provisioner-5db678dcd9-xqcxg   0/1       ContainerCreating   0          27m

**Comment by madannuthi** [comment] 2019-07-16 05:38
Hi @midN can u specify steps on how to deploy this. when i tried to clone your repo and apply the manifest file. (by filling out my env details in it) the container is not getting created.
NAME READY STATUS RESTARTS AGE
efs-provisioner-5db678dcd9-xqcxg 0/1 ContainerCreating 0 27m

**Comment by midN** [comment] 2019-07-16 13:45
@saikiran243 @madannuthi Check the pod logs, there is something missing from your deployment.
Did you create EFS and specify a reachable EFS?

Deployment process did not change, only couple of extra options were added

**Comment by madannuthi** [comment] 2019-07-17 10:31
@midN  Thanks for the quick response we will try this option and get back  to you.

**Comment by midN** [comment] 2019-07-17 15:01
@saikiran243 It's right there.........
```
17m Warning ProvisioningFailed PersistentVolumeClaim storageclass.storage.k8s.io "aws-efs" not found
```
You did not create https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/deploy/class.yaml .

**Comment by saikiran243** [comment] 2019-07-18 13:30
Hi @midN thanks for the update,
l am doing following steps.
1)Cloned your Repo.
2)Created a Docker image out of it
3) pushed to my registry
4) adding this image in the manifest file for the Deployment of efs-provisioner
iam able to create the provisioner pod
**pv,pvc are able to create. but the issue is the directory created with the name in the efs is  (pv+pvc) which was in the same manner of the earlier where i used without "SKIP_PVC_NAMED_PATH",
"KEEP_PV_PATH" options in the efs provisioner pod creation.
same result even changing to "False"  for the PATH Parameters**
**### My Aim was to claim the persistent volume to the Root folder and skip this creation of newfolder**
**can u please help me where iam getting wrong in achieving the results.** 
[root@server-01 ]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                   STORAGECLASS   REASON    AGE
pvc-a8b00c17-a956-11e9-af8a-0abe9j22a154   10Gi       RWX            Delete           Bound     namespace/pvc-test-1 aws-efs                  12m
pvc-a8b0cf53-a956-11e9-af8a-0abe9j22a154   10Gi       RWX            Delete           Bound     namespace/pvc-test-2      aws-efs                  12m

in the EFS the directories created are
pvc-test-1-pvc-a8b00c17-a956-11e9-af8a-0abe9j22a154
pvc-test-2-a8b0cf53-a956-11e9-af8a-0abe9j22a154


================Deployment_manifest_file==================
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
data:
  file.system.id: fs-11111
  aws.region: us-east-1
  provisioner.name: test/aws-efs
  dns.name: "fs-11111.efs.us-east-1.amazonaws.com"
  skip.pvc.named.path: ""
  keep.pv.path: ""
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: 123456.dkr.ecr.us-east-1.amazonaws.com/efspv:v1.0
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: aws.region
            - name: DNS_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: dns.name
                  optional: true
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: provisioner.name
            - name: SKIP_PVC_NAMED_PATH
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: skip.pvc.named.path
                  optional: false
            - name: KEEP_PV_PATH
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: keep.pv.path
                  optional: false
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-11111.efs.us-east-1.amazonaws.com
            path: /
---

**Comment by midN** [comment] 2019-07-18 13:41
@saikiran243 Your `skip.pvc.named.path` and `keep.pv.path` are empty strings, false.
```
keep.pv.path: true
skip.pvc.named.path: true```

**Comment by madannuthi** [comment] 2019-07-19 05:19
@midN  we tried by keeping **skip.pvc.named.path and keep.pv.path** are set to **true** like below but still we are getting the result.

keep.pv.path: true
skip.pvc.named.path: true

[root@server-01 ]# kubectl get pv
NAME CAPACITY ACCESS MODES RECLAIM POLICY STATUS CLAIM STORAGECLASS REASON AGE
pvc-a8b00c17-a956-11e9-af8a-0abe9j22a154 10Gi RWX Delete Bound namespace/pvc-test-1 aws-efs 12m
pvc-a8b0cf53-a956-11e9-af8a-0abe9j22a154 10Gi RWX Delete Bound namespace/pvc-test-2 aws-efs 12m

in the EFS the directories created are
pvc-test-1-pvc-a8b00c17-a956-11e9-af8a-0abe9j22a154
pvc-test-2-a8b0cf53-a956-11e9-af8a-0abe9j22a154

**Comment by pnalamati-rms** [comment] 2019-07-29 14:20
@midN I tried the image(m1dn/efs-provisioner:v1.0) that is in docker hub. The PVC volume folder is still getting created. I set keep.pv.path: true, skip.pvc.named.path: true  and image: m1dn/efs-provisioner:v1.0 in manifest file.

**Comment by prakash-nvs** [comment] 2019-07-29 14:35
@midN I tried the image(m1dn/efs-provisioner:v1.0) that is in docker hub. The PVC volume folder is still getting created. I set keep.pv.path: true, skip.pvc.named.path: true and image: m1dn/efs-provisioner:v1.0 in manifest file.

**Comment by midN** [comment] 2019-07-29 19:24
@prakash-nvs post your configmap and deployment describe output

**Comment by pnalamati-rms** [comment] 2019-07-29 23:21
@midN Here is config and deployment: 
kubectl describe configmap efs-provisioner -n tenant2-workflows
Name:         efs-provisioner
Namespace:    tenant2-workflows
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","data":{"aws.region":"us-east-1","dns.name":"fs-1234efd0.efs.us-east-1.amazonaws.com","file.system.id":"fs-1234efd0","k...

Data
====
keep.pv.path:
----
true
provisioner.name:
----
rms.com/aws-efs
skip.pvc.named.path:
----
true
aws.region:
----
us-east-1
dns.name:
----
fs-1234efd0.efs.us-east-1.amazonaws.com
file.system.id:
----
fs-1234efd0
Events:  <none>

Deployment:

describe deployment efs-provisioner -n tenant2-workflows
Name:               efs-provisioner
Namespace:          tenant2-workflows
CreationTimestamp:  Sun, 28 Jul 2019 17:33:11 -0700
Labels:             app=efs-provisioner
Annotations:        deployment.kubernetes.io/revision: 1
                    kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"efs-provisioner","namespace":"tenant2-workflow...
Selector:           app=efs-provisioner
Replicas:           1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:  app=efs-provisioner
  Containers:
   efs-provisioner:
    Image:      m1dn/efs-provisioner:v1.0
    Port:       <none>
    Host Port:  <none>
    Environment:
      FILE_SYSTEM_ID:       <set to the key 'file.system.id' of config map 'efs-provisioner'>       Optional: false
      AWS_REGION:           <set to the key 'aws.region' of config map 'efs-provisioner'>           Optional: false
      DNS_NAME:             <set to the key 'dns.name' of config map 'efs-provisioner'>             Optional: true
      PROVISIONER_NAME:     <set to the key 'provisioner.name' of config map 'efs-provisioner'>     Optional: false
      SKIP_PVC_NAMED_PATH:  <set to the key 'skip.pvc.named.path' of config map 'efs-provisioner'>  Optional: false
      KEEP_PV_PATH:         <set to the key 'keep.pv.path' of config map 'efs-provisioner'>         Optional: false
    Mounts:
      /persistentvolumes from pv-volume (rw)
  Volumes:
   pv-volume:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    fs-1234efd0.efs.us-east-1.amazonaws.com
    Path:      /
    ReadOnly:  false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   efs-provisioner-77567769f4 (1/1 replicas created)
Events:          <none>
can u please let me know if you find any issue.
Thanks.

**Comment by prakash-nvs** [comment] 2019-07-29 23:27
@midN Here is configmap and deployment:
 kubectl describe configmap efs-provisioner -n tenant2-workflows
 Name: efs-provisioner
 Namespace: tenant2-workflows
 Labels: 
 Annotations: kubectl.kubernetes.io/last-applied-configuration:
 {"apiVersion":"v1","data":{"aws.region":"us-east-1","dns.name":"fs-1234efd0.efs.us-east-1.amazonaws.com","file.system.id":"fs-1234efd0","k...

Data

keep.pv.path:

true
 provisioner.name:

rms.com/aws-efs
 skip.pvc.named.path:

true
 aws.region:

us-east-1
 dns.name:

fs-1234efd0.efs.us-east-1.amazonaws.com
 file.system.id:

fs-1234efd0
 Events: 

Deployment:

describe deployment efs-provisioner -n tenant2-workflows
 Name: efs-provisioner
 Namespace: tenant2-workflows
 CreationTimestamp: Sun, 28 Jul 2019 17:33:11 -0700
 Labels: app=efs-provisioner
 Annotations: deployment.kubernetes.io/revision: 1
 kubectl.kubernetes.io/last-applied-configuration:
 {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"efs-provisioner","namespace":"tenant2-workflow...
 Selector: app=efs-provisioner
 Replicas: 1 desired | 1 updated | 1 total | 1 available | 0 unavailable
 StrategyType: Recreate
 MinReadySeconds: 0
 Pod Template:
 Labels: app=efs-provisioner
 Containers:
 efs-provisioner:
 Image: m1dn/efs-provisioner:v1.0
 Port: 
 Host Port: 
 Environment:
 FILE_SYSTEM_ID: <set to the key 'file.system.id' of config map 'efs-provisioner'> Optional: false
 AWS_REGION: <set to the key 'aws.region' of config map 'efs-provisioner'> Optional: false
 DNS_NAME: <set to the key 'dns.name' of config map 'efs-provisioner'> Optional: true
 PROVISIONER_NAME: <set to the key 'provisioner.name' of config map 'efs-provisioner'> Optional: false
 SKIP_PVC_NAMED_PATH: <set to the key 'skip.pvc.named.path' of config map 'efs-provisioner'> Optional: false
 KEEP_PV_PATH: <set to the key 'keep.pv.path' of config map 'efs-provisioner'> Optional: false
 Mounts:
 /persistentvolumes from pv-volume (rw)
 Volumes:
 pv-volume:
 Type: NFS (an NFS mount that lasts the lifetime of a pod)
 Server: fs-1234efd0.efs.us-east-1.amazonaws.com
 Path: /
 ReadOnly: false
 Conditions:
 Type Status Reason


Available True MinimumReplicasAvailable
 OldReplicaSets: 
 NewReplicaSet: efs-provisioner-77567769f4 (1/1 replicas created)
 Events: 
 can u please let me know if you find any issue.
 Thanks.

**Comment by midN** [comment] 2019-07-30 13:31
@prakash-nvs Don't see anything wrong, did you create the Deployment before updating configmap maybe and didn't roll deployment afterwards?
Can you exec into container and check if ENVs are set correctly by executing env:
```
kubectl exec -ti POD_NAME env
```

**Closed** 2019-10-24 22:19 UTC
