### ISSUE TITLE
EFS Provisioner - Non-root procs get permission-denied

### ISSUE THREAD

**Issue by etotheipi** [kubernetes-incubator/external-storage#147] opened 2017-06-02 18:48 UTC
HEAD of this repo, external EFS provisioner
Kubernetes 1.6.4

So far, we have gotten stuck trying to run a variety of things with EFS-provisioned volumes.  It has worked for every container that runs processes as root inside the container, it has no problem accessing dynamically-provisioned mount points in the EFS volume.

However, we're running grafana and elasticsearch, both of which (responsibly) de-escalate permissions to non-root using `gosu grafana /run.sh` or `gosu elasticsearch /run.sh`.  They get permission-denied errors when attempting to write to the PVC.   I have `exec`d into the containers and confirmed that I can touch files in the PVC as root, and get errors when I `gosu <non-root> touch file.txt`.  

In the case of grafana, I was able to modify the entrypoint to remove `gosu grafana`, which worked and grafana is happy.  However, elasticsearch refuses to run as root, which puts me in an awkward position.

I have tried using the GID annotation in the PVC: `pv.beta.kubernetes.io/gid: <gid of non-root group>`, however the documentation says that applies only to the user of the of entrypoint process of the first container:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#access-control

In each case, the entrypoint scripts are run as root, but de-escalate at the end of the script.  I'm not sure if this would specifically solve my problem even if that wasn't the case, though.

In both cases above, the entrypoint script is changing the permissions of the PVC mount before attempting to run, and I can see those uid/gid changes when I browse the EFS volume in another pod.  However, even after such modifications the non-root user with the same GID cannot write to it.

This may not be specific to EFS as it is NFS and NFS PV mounts in general.

**Comment by wongma7** [comment] 2017-06-02 19:48
I'm still parsing this and your kubernetes/charts issue but there's some immediate stuff I can clarify:

`pv.beta.kubernetes.io/gid: <gid of non-root group>` is an annotation that you put on the PV, not PVC, that ensures the share is created with group owner equal to the annotation's value. AND it ensures that the pod consuming the share (the entrypoint of the pod's container) runs as a member of that group. The EFS provisioner already does this for you automatically: notice how the influxdb share has owner 2005 and zookeeper 2000. You are basically correct about why it doesn't have any benefit for influxdb/grafana

Now, I'd say this is an NFS problem in general, but it's totally possible to mitigate on the EFS provisioner's end. So please bear with me, I'm reading up...I don't know what gosu is, etc.

**Comment by etotheipi** [comment] 2017-06-02 20:05
Just to quickly clarify: gosu is a replacement for using sudo to run a
process as a different user.  The mechanics of it or why to use it over
sudo probably isn't relevant for our purposes here.

Thanks for looking into this so quickly!

**Comment by wongma7** [comment] 2017-06-02 20:22
The issue is that the EFS provisioner creates directories with permissions `---rws--x`, under the wrong assumption that its GID security will work everywhere. The owner permissions take precedence over the group permissions, so that's why grafana (and elasticsearch?) has no permission to do anything, even though it's both the user owner and group owner. Grafana chowns the directory to what it wants but it doesn't chmod it, which is fair. (IMO maybe it could OR the permissions by 700 but idk what other implications that would have).

The simplest solution is for EFS provisioner to make directories with permissions 771 , but I *think* I made it create directories 071 for a reason. The assumption of "do security via supplemental groups" is well embedded into the kubernetes/openshift way of doing NFS, so I will have to think about this..

**Comment by wongma7** [comment] 2017-06-02 20:37
alright I don't think there's any harm in creating directories with 771, I will do it.

**Comment by etotheipi** [comment] 2017-06-02 20:57
Great!  Practically speaking, if you didn't want a particular process to
have access to the PV/PVC, you wouldn't have mounted it to the pod in the
first place.  That logic fails if you have pods that have a bunch of
different processes inside, but those are the exception and I assume that
in such cases the pod can run a process to change the permissions for their
purpose.

Thanks!  You've just eliminated quite a bit of stress from my app
kuberization activities.

**Comment by wongma7** [comment] 2017-06-02 21:05
I've just pushed it to the latest tag; let me know if it works.

**Comment by etotheipi** [comment] 2017-06-02 21:18
To be clear, you just updated: `quay.io/external_storage/efs-provisioner:latest` ?

**Comment by wongma7** [comment] 2017-06-02 21:20
Yes, that

**Comment by wongma7** [comment] 2017-06-12 20:33
Assume this works; closing!

**Closed by wongma7** 2017-06-12 20:33 UTC
