### ISSUE TITLE
Need an Equivalent of K8s func GetAllZones

### ISSUE THREAD

**Issue by pospispa** [kubernetes-incubator/external-storage#242] opened 2017-07-14 16:22 UTC
K8s provides [func GetAllZones](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_instances.go#L248) that returns all the zones in which K8s cluster nodes are running.

Some types of storage can be zone-aware, i.e. the storage needs to be provisioned in a particular zone.

In case a user does not specify in which zone the storage shall be provisioned an external provisioner may want to provision in a random zone in which the K8s cluster has a running node.

That's why having an equivalent of the [K8s func GetAllZones](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_instances.go#L248) is beneficial.

Note: [a Trello card](https://trello.com/c/PBLTeegt/455-3-manila-external-provisioner-add-func-getallzones-into-the-external-provisioner-library) for the same feature.

**Comment by wongma7** [comment] 2017-07-14 16:49
I don't think we should abstract this function and implement our own "mini" cloudproviders as part of the library. I think the cloudprovider abstraction is overkill for external provisioners (and volume plugins too) and IMO any cloud API calls should be implemented by each provisioner by & for itself.

I have not been following it that closely but the above approach is basically what the proposal on moving cloud-providers out-of-tree appears to suggest https://github.com/kubernetes/community/blob/28e993f5184e425eb1f1e71d4ea30cba9c166e44/contributors/design-proposals/cloud-provider-refactoring.md#5-strategy-for-refactoring-volumes . Each external provisioner/plugin should figure out how to talk to the cloud on its own and encapsulate all that stuff.

If it so happens that multiple provisioners talk to the same cloud and they need the same sorts of abstractions, then we can consider moving those functions into the library. But the point I'm trying to make is that we should avoid copying the cloudprovider pattern from the start because it's not necessary

Anyway, alternatively for this particular case we may simply mandate that the user specify "zones" in their StorageClass, what do you think?

**Comment by wongma7** [comment] 2017-07-14 17:31
Hm, here's another way to think of it. That GetAllZones relies on gce.managedZones, which is filled in by cloudconfig. So an external provisioner would need to be configured at deploy time in the same way, via an argument or configmap probably, with e.g. the list of zones

**Comment by pospispa** [comment] 2017-09-22 12:50
@wongma7 my assumption is that running Kubernetes cluster keeps list of it's nodes. This information is available in Kubernetes API as [`NodeList`](https://kubernetes.io/docs/api-reference/v1.7/#nodelist-v1-core). So it should be possible to get the `NodeList` from Kubernetes API, parse information of individual [nodes](https://kubernetes.io/docs/api-reference/v1.7/#node-v1-core) and get labels for each node from its [metadata](https://kubernetes.io/docs/api-reference/v1.7/#objectmeta-v1-meta).

I assume that the [nodes are labeled](https://kubernetes.io/docs/admin/multiple-zones/#nodes-are-labeled) and the labels contain information in which zone a particular node is.

So as external provisioner library already watches Kubernetes API for PVCs it can also watch nodes. I believe that such extenal provisioner library feature may be useful for several external provisioners.

Please, what do you think about this idea?

**Comment by pospispa** [comment] 2017-09-22 17:42
> No other provisioner in this repo so far has needed to look at nodes.

So AFAIK no other external provisioner supports multiple zones until now.

One of the Kubernetes features in [AWS](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#aws), [GCE](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#gce) and [Cinder](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#openstack-cinder) plugins is that if no zones are specified in the Storage Class, volumes are generally round-robin-ed across all active zones where Kubernetes cluster has a node.

The Manila provisioner aims to have the same feature so that's why it needs to `GetAllZones`.

***

Kubernetes assumes that the mapping between Nova and Manila availability zones must be 1:1. So it's possible to read the list of zones either from Kubernetes nodes or from Manila as both must be the same.

**Comment by pospispa** [comment] 2017-09-29 16:53
I'm sorry I failed to explain the problem. Please, let me explain it from scratch.

***

1. Let's assume there is a storage class that doesn't have any zone(s) specified as zone(s) parameter is optional.
2. Let's assume a user creates a PVC that references the storage class so a PV shall be provisioned dynamically.
3. In which zone should be such PV provisioned?
4. In a zone in which the K8s cluster has at least one active node. So the provisioner needs to get a list of zones in which K8s cluster has at least one currently active node. The list of zones is a dynamic information because nodes can go up and down and new nodes can be added to the cluster and similarly existing nodes can be removed from the cluster.
5. Where can we get the list of zones from? Where is the source of truth of this dynamic information? This information is in K8s API as [NodeList](https://kubernetes.io/docs/api-reference/v1.7/#nodelist-v1-core) that can be parsed to get the current list of zones in which K8s cluster has at least one currently active node. @wongma7 please, do you agree?

The list of zones in which K8s cluster has at least one currently active node cann't be given to external provisioner as a static configuration because if all nodes in a zone become unavailable there will be a risk that the provisioner can provision a PV in a zone without any active nodes so the provisioned PV will be useless for the user because the pod in which is the PVC used cann't be scheduled into the PV's zone because there're no active nodes.

The list of zones cann't be read from a storage API (if it's available) because the storage may be available in zone(s) in which the K8s cluster doesn't have any currently active node.

@wongma7 please, do you agree with the above?

**Comment by msau42** [comment] 2017-09-29 17:03
We tried to go with this same approach for in-tree provisioning, but there were concerns brought up around whether we could really trust the Node's information, and layer violation.  See kubernetes/kubernetes#50115

**Comment by wongma7** [comment] 2017-09-29 18:21
I understand the problem.

I don’t understand what is being expected of me here. It isn’t my concern how the attempted solution is implemented. I’ve simply expressed a reluctance to include cloud specific code in the library, because I think it is out of scope. Regardless of where the code lives, somebody is going to need to write it, and it won’t be me

**Comment by pospispa** [comment] 2017-10-02 10:43
> I don’t understand what is being expected of me here. It isn’t my concern how the attempted solution is implemented. I’ve simply expressed a reluctance to include cloud specific code in the library, because I think it is out of scope. Regardless of where the code lives, somebody is going to need to write it, and it won’t be me.

I tried to think out loud how to approach this issue. I was wavering among several approaches, but currently I think that querying K8s API for [NodeList](https://kubernetes.io/docs/api-reference/v1.7/#nodelist-v1-core) is the right approach.

I'd like to get validation that this approach makes sense to others before actual implementation.

***

Regarding the implementation: extending the library in such a way that it also watches nodes feels as the easiest way for me.

I currently don't know how to implement it directly into a provisioner without extending the library. However, I've got some hints from @tsmetana.

**Comment by pospispa** [comment] 2017-10-02 13:08
> We tried to go with this same approach for in-tree provisioning, but there were concerns brought up around whether we could really trust the Node's information, and layer violation. See kubernetes/kubernetes#50115

@msau42 thank you for pointing me to the kubernetes/kubernetes#50115 issue.

It's useful for me to know that [PR #52322](https://github.com/kubernetes/kubernetes/pull/52322) tried the same approach but failed because of not enough access rights to K8s API. To see the follow-up discussion: [where is "the right source of true for zones"](https://github.com/kubernetes/kubernetes/issues/50115#issuecomment-331527894). And in addition, to know that [listing nodes is expensive](https://github.com/kubernetes/kubernetes/pull/52322#issuecomment-331519659). And finally, that there's a design: [reduce scope of node on node object](https://github.com/kubernetes/community/pull/911/files).

It seems that it'll be better for me to wait until issue https://github.com/kubernetes/kubernetes/issues/50115 is fixed.

**Comment by wongma7** [comment] 2017-10-03 06:49
Maybe you could mandate that the storageclass must have a zone parameter specified, at least until the issue is solved. If I’m reading the linked issue correctly, it’s mostly a problem because people use the default storage class which can’t possibly be populated with any zone information at cluster bootstrap time. I doubt zones change often enough that the solution has to be super good, but I don’t know.

Anyway, sorry if i came off as dismissive: certainly I can help as well, but I mean to say I know nothing outside my library bubble, I.e. nothing about openstack zones

**Comment by msau42** [comment] 2017-10-03 13:27
Yes, the primary workaround is to define the zones in the StorageClass.  The main issue is that you can dynamically add/remove new zones to your cluster, so we can't just use the current zones at cluster creation time.

**Comment by pospispa** [comment] 2017-10-04 10:07
There is [Generic Storage Topology solution that works well with CSI and Local Storage](https://docs.google.com/spreadsheets/d/1t4z5DYKjX2ZDlkTpCnp18icRAQqOE85C1T1r2gqJVck/edit#gid=1993207982) design targeted for K8s 1.9 in SIG storage tracking spreadsheet. I believe the design should work also for external provisioners. Currently, I'm not in a hurry so I can wait for the design.

**Closed** 2018-06-15 17:46 UTC
